version: "3"

services:
  db:
    image: postgres:16-alpine
    build:
      context: db
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
  app:
    # image: rheens/mattermost-app:v9.2.0
    ports:
      - $MATTERMOST_HOST_PORT:$MATTERMOST_DOCKER_PORT
    build:
      context: ./app
      args:
        - MM_VERSION=v9.2.0
        - GOOS=linux
        - GOARCH=arm64
        - MATTERMOST_DOCKER_PORT=$MATTERMOST_DOCKER_PORT
        - PUID=$PUID
        - PGID=$PGID
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
